export const CART_ADD_ITEM="CART_ADD_ITEM"
export const CART_REMOVE_ITEM ="CART_REMOVE_ITEM"

export const CARD_SAVE_SHIPPING = "CARD_SAVE_SHIPPING"
export const CARD_SAVE_PAYMENT = "CARD_SAVE_PAYMENT"
